/**
 * Pull the latest Instagram posts into public/assets/insta/.
 *
 *   IG_TOKEN=... node tools/fetch-insta.mjs          # fetch posts + images
 *   IG_TOKEN=... node tools/fetch-insta.mjs --refresh # extend the token 60 days
 *
 * THE TOKEN NEVER GOES IN A FILE. It is read from the environment, so it lives
 * in a Vercel env var or a GitHub Actions secret and never in the repo, never in
 * the bundle. Anything shipped to the browser is public — an Instagram token in
 * a JS bundle is a token you have given away.
 *
 * WHY THIS DOWNLOADS THE PICTURES RATHER THAN LINKING THEM
 * `media_url` from the API is a SIGNED CDN link with an expiry baked in. Writing
 * those into the manifest makes the strip work for a few weeks and then go
 * silently blank: no error, no console warning, just an empty row. Meta's own
 * guidance is to persist the image yourself, so that is what happens here — the
 * manifest only ever contains local paths.
 *
 * WHICH API
 * Instagram API with Instagram Login, which is the path for a Professional
 * account that is NOT tied to a Facebook Page. The old Basic Display API was
 * shut down in December 2024 and is not coming back.
 *
 * THE 60-DAY PROBLEM
 * Tokens last 60 days and do not auto-renew. `--refresh` extends one by another
 * 60 (allowed any time after the token is 24 hours old) and prints the new
 * value, which then has to be stored back wherever the old one lived. Run it on
 * a schedule well inside the window — 50 days, not 59 — or one missed run means
 * re-authenticating by hand.
 */
import { mkdir, writeFile, readdir, unlink } from 'node:fs/promises';
import { join } from 'node:path';

const TOKEN = process.env.IG_TOKEN;
const OUT_DIR = 'public/assets/insta';
const MANIFEST = join(OUT_DIR, 'posts.json');
const PROFILE = process.env.IG_PROFILE || 'https://www.instagram.com/shibli_afaq';
const LIMIT = Number(process.env.IG_LIMIT || 12);

if (!TOKEN) {
  console.error('IG_TOKEN is not set. Read it from your environment, never from a file.');
  process.exit(1);
}

/** Extend the token by another 60 days and print the replacement. */
async function refresh() {
  const url = 'https://graph.instagram.com/refresh_access_token'
    + `?grant_type=ig_refresh_token&access_token=${encodeURIComponent(TOKEN)}`;
  const r = await fetch(url);
  const j = await r.json();
  if (!r.ok || !j.access_token) {
    console.error('refresh failed:', JSON.stringify(j));
    process.exit(1);
  }
  const days = Math.round((j.expires_in || 0) / 86400);
  console.log(`new token valid ~${days} days. Store it wherever the old one lived:`);
  console.log(j.access_token);
}

/* An album has no media_url of its own and a video's media_url is the film, not
   a picture — thumbnail_url is the frame. Falling back through both means one
   code path covers all three media types. */
function pictureOf(post) {
  if (post.media_type === 'VIDEO') return post.thumbnail_url || null;
  return post.media_url || post.thumbnail_url || null;
}

async function run() {
  const fields = 'id,caption,media_type,media_url,thumbnail_url,permalink,timestamp';
  const url = `https://graph.instagram.com/me/media?fields=${fields}&limit=${LIMIT}`
    + `&access_token=${encodeURIComponent(TOKEN)}`;

  const res = await fetch(url);
  const body = await res.json();
  if (!res.ok || !Array.isArray(body.data)) {
    console.error('fetch failed:', JSON.stringify(body));
    process.exit(1);
  }

  await mkdir(OUT_DIR, { recursive: true });

  const posts = [];
  const keep = new Set(['posts.json']);

  for (const p of body.data) {
    const pic = pictureOf(p);
    if (!pic) continue;                       // nothing displayable, skip quietly

    const name = `ig-${p.id}.jpg`;            // Instagram serves JPEG
    const img = await fetch(pic);
    if (!img.ok) { console.warn(`skipped ${p.id}: image ${img.status}`); continue; }
    await writeFile(join(OUT_DIR, name), Buffer.from(await img.arrayBuffer()));
    keep.add(name);

    posts.push({
      image: `/assets/insta/${name}`,
      permalink: p.permalink,
      // One line: the strip clamps to two, and a full Instagram caption is an essay.
      caption: (p.caption || '').split('\n')[0].slice(0, 140),
      timestamp: p.timestamp,
    });
  }

  /* Old pictures are removed, or the folder grows forever and the repo carries
     every post ever made. Only files this run did not write are touched. */
  for (const f of await readdir(OUT_DIR)) {
    if (!keep.has(f)) await unlink(join(OUT_DIR, f));
  }

  await writeFile(MANIFEST, JSON.stringify({
    _comment: [
      'GENERATED by tools/fetch-insta.mjs — hand edits are overwritten.',
      'Images are local paths on purpose: Instagram media_url links are signed',
      'and expire, so linking them would make the strip go blank with no error.',
    ],
    generated: new Date().toISOString(),
    profile: PROFILE,
    posts,
  }, null, 2) + '\n');

  console.log(`wrote ${posts.length} posts and ${keep.size - 1} images to ${OUT_DIR}`);
}

if (process.argv.includes('--refresh')) await refresh();
else await run();
